### ISSUE TITLE
Thank You. Thank you. Thank you.

### ISSUE THREAD

**Issue by scyto** [nicojeske/MasterVolumeSync#1]
Thank you for making this public.
I have been trying to solve this issue for over a decade.
My volume control now works,  including for games that are being DD encoded!!!

WTF Microsoft or Creative couldn't do this is beyond me.

**Comment by scyto** [comment]
PS might me good to document exactly which .net 6 framework needed to be downloaded - aka the desktop one not the others.

**Comment by Slion** [comment]
@nicojeske Awesome piece of software mate 🍺 thank you indeed!
