### ISSUE TITLE
Feature Request: Windows Mute Button should mute volume 

### ISSUE THREAD

**Issue by scyto** [nicojeske/MasterVolumeSync#3]
Not sure you are taking feature requests :-)  but here goes.

Could you make it that when the windows mute button is pressed (for example the mute button on the keyboard, or the mute command on the mute button the windows control) it would mute what you hear?

![image](https://user-images.githubusercontent.com/11369180/175717170-defe6403-8483-4ac6-a042-b722ea89217b.png)

What happens now is the volume control in windows shows mute but volume doesn't change.

**Comment by nicojeske** [comment]
Luckily I could add this by only adding 1 line of code (and wasting 20 minutes trying to get the setup project working again) :D

Just released [version 1.0.7](https://github.com/nicojeske/MasterVolumeSync/releases/tag/1.0.7)

Please try it out and let me now if it also works on your end.

**Comment by scyto** [comment]
Works perfectly, thanks!
