### ISSUE TITLE
Mute/Unmute What U Hear when no audio detected

### ISSUE THREAD

**Issue by Slion** [nicojeske/MasterVolumeSync#4]
To tackle the issue described [here](https://slions.net/threads/sound-blaster-z-survival-guide.94/#302-Empty+audio+stream) we could mute/unmute What U Hear device when no audio is detected. I'm thinking we could use code from [SPDIF Keep-Alive](https://github.com/handruin/spdif-ka) to detect when no audio is being played.

**Comment by scyto** [comment]
this would need to be an option, i am using [sound keeper](https://github.com/vrubleg/soundkeeper/) to do the same, i wouldn't want anything muted when there is no audio detcted due to the way my speakers work.

**Comment by Slion** [comment]
Definitely, was doing more thinking on that and I don't think it would be practical anyway. I mean if you really mean to mute your PC it would unmute it as soon as audio is being played. Though I guess we could keep track of the fact that we auto muted the device and thus not unmute it if we didn't. Would still be tricky to implement and could be somewhat confusing to use.

**Comment by nicojeske** [comment]
It seems that implementing such a feature would not be straightforward and may not align with the scope of the project. However, if someone is interested in working on this, they could certainly create a pull request to add it as an optional setting.
