### ISSUE TITLE
Starts for a moment then crashes

### ISSUE THREAD

**Issue by slugface08** [nicojeske/MasterVolumeSync#6]
Worked fine for a week. Now when trying to open it runs for one second on Task Manager then crashes accompanied by a "Windows Problem Reporting" message. Please Advise. Thanks.

**Comment by slugface08** [comment]
have tried re installing many times i dont know whats wrong with it

**Comment by nicojeske** [comment]
Hi @slugface08 

Thank you for reporting this issue. It could be that you're experiencing a problem similar to the one described in Issue #2 . I recommend you try following the troubleshooting steps provided there, as it might be related to your current situation.

Please let me know if the solution from Issue #2 resolves your problem.

**Comment by slugface08** [comment]
solved it by reformatting the drive. Thanks!Sent from my iPhoneOn Apr 18, 2023, at 9:17 AM, Nico Jeske ***@***.***> wrote:﻿
Hi @slugface08
Thank you for reporting this issue. It could be that you're experiencing a problem similar to the one described in Issue #2 . I recommend you try following the troubleshooting steps provided there, as it might be related to your current situation.
Please let me know if the solution from Issue #2 resolves your problem.
